### ISSUE TITLE
Convert slide deck to PowerPoint (pptx) that consists of rendered images

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-cli#107]
By using [officegen](https://github.com/Ziv-Barber/officegen), we might convert from Marpit / Marp Markdown into PowerPoint slide that consists of pre-rendered images.

It's very useful for mixing a traditional presentation deck and the deck made by Marp. In addition, it could use PowerPoint's presenter tool with [Marpit's presenter notes](https://marpit.marp.app/usage?id=presenter-notes).

Exporting PowerPoint deck was mentioned in the old Marp app by yhatt/marp#23. We'll make it wake up.

I suppose it would have to start working after than implemented #71.

### ToDo

- [x] Implement #71
- [x] Allow `--pptx` option and pptx extension in `-o` option (`-o foobar.pptx`)
  - [x] Add each rendered images to slides
  - [x] Support presenter note by [comments parsed by Marpit](https://marpit.marp.app/usage?id=presenter-notes)

---

:warning: People would expect re-editable contents in converted pptx. But it's still super difficult to convert into them with keeping the exact slide design, and ***there is no solution in FLOSS***.

[Adobe Acrobat](https://acrobat.adobe.com/) can convert the exported PDF into pptx that includes re-editable contents, and keeps the design to some extent.

**Comment by yhatt** [comment]
I'm comparing 2 packages for creating pptx. At the moment, I would choose PptxGenJS because a generated pptx has compatibility with many office suites.

## [officegen](https://github.com/Ziv-Barber/officegen)

### Pros

- Well tested, and supported by many packages.
- Probably active, and stars earned over 1.5k.
- Open-source licensed by MIT.

### Cons

- A bit lacked documentation.
- Speaker notes does not apply when opening in Keynote app.

## [PptxGenJs](https://github.com/gitbrent/PptxGenJS)

### Pros

- Universal JS: Supports many environments.
- Support background image for slide page and can create PPTX similar to GitPitch's PowerPoint support.
- Most likely active, and already reached stable version.
- Open-source licensed by MIT.

### Cons

- npm package includes unnecessary 20MB examples.
- It requires a bit trick to enable TypeScript definition.
- I fear that it was not included any tests.
