### ISSUE TITLE
Consider migration CI for Windows into GitHub Actions

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-cli#132]
Marp team's primary CI won't change from CircleCI, but I think a new bulit-in CI/CD for [GitHub Actions](https://github.com/features/actions) is easier to maintain than Azure Pipelines, that is the current secondary CI for Marp team for running tests and builds in Windows environment.

In fact, [GitHub Actions is using Azure Pipelines backend](https://twitter.com/natfriedman/status/1159526215658561536).

### ToDo

- [x] Wait until enabled GitHub Actions for Marp team (-Nov, 13)
- [x] Set up GitHub Actions
  - [x] Test in Windows environment
  - [x] Create Windows binary via pkg
  - [x] Upload packaged asset of standalone binary for Windows to GitHub release page

> [CircleCI has started supporting Windows environment too.](https://circleci.com/blog/windows-general-availability-announcement/) It provides only to user of performance plan, and not yet provided free plan to OSS projects. We might re-migrate to CircleCI when Windows environment in CircleCI could use in OSS project in future.
