### ISSUE TITLE
Convert slide deck to multiple images

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-cli#71]
As I have been pointed out at #68, it is great to get converting the slide deck into multiple images. We want to provide the easiest way to create sequence images.

### ToDo

- [x] Refactor `Converter` to support multiple output
- [x] Consider option to output sequence images (`--images`?)
- [ ] Output only specified page(s) via `--page` option (In another PR)
